# Generated by Django 2.1.3 on 2018-11-18 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=10, null=True)),
                ('upload_time', models.DateTimeField(null=True)),
                ('print_start_time', models.DateTimeField(null=True)),
                ('print_end_time', models.DateTimeField(null=True)),
                ('print_time', models.CharField(max_length=20, null=True)),
                ('printer_name', models.CharField(max_length=20, null=True)),
                ('file_path_stl', models.CharField(max_length=1000, null=True)),
                ('file_path_obj', models.CharField(max_length=1000, null=True)),
                ('special_marker', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField()),
                ('grade', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintQueueManager.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='fk_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintQueueManager.Profile'),
        ),
        migrations.AddField(
            model_name='featuredprint',
            name='fk_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintQueueManager.Job'),
        ),
    ]
